name: sossego_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  asp: ^2.0.3
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  google_maps_flutter: ^2.12.2
  google_maps_flutter_web: ^0.5.12
  intl: ^0.20.2
  js: ^0.7.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/